apiVersion: v1
kind: Service
metadata:
  name: todoapp-service
  namespace: todoapp
  labels:
    job: todoapp
    app: todoapp
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: http
